services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"

  api:
    build: ./api
    ports:
      - "5001:5001"
    environment:
      MONGO_URI: mongodb://mongo:27017/mediascore
    depends_on:
      - mongo

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - api

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
